"""Limine installation and configuration.

The kernel command line is where encryption, hibernation and the Btrfs layout all
have to agree. Getting one parameter wrong here produces a machine that reaches
the bootloader and then stops, which is the hardest kind of failure to diagnose
from inside the installer.
"""

from __future__ import annotations

from .. import log
from ..command import CommandRunner, get_runner
from ..models import InstallConfig
from ..target import TargetSystem

#: Limine's own files live here; the ESP is mounted at /boot.
LIMINE_DIRECTORY = "boot/EFI/BOOT"
LIMINE_CONFIG = "boot/limine.conf"


def kernel_cmdline(
    config: InstallConfig,
    luks_uuid: str,
    mapper_path: str,
    resume_offset: str | None,
) -> str:
    """Parameters the kernel needs to find and open its own root filesystem."""
    parts: list[str] = []

    if config.encryption.enabled:
        # sd-encrypt reads this; it is what lets the initramfs open the container
        # before a root filesystem exists.
        parts.append(f"rd.luks.uuid={luks_uuid}")
        parts.append(f"root={mapper_path}")
    else:
        parts.append(f"root=PARTUUID={luks_uuid}")

    # Without the subvol the kernel mounts the Btrfs top level, which contains
    # the subvolumes rather than a root filesystem, and boot fails confusingly.
    parts.append("rootflags=subvol=@")
    parts.append("rw")

    if config.swap.hibernation_enabled and resume_offset:
        # Both are required. resume alone names the device but not where in it
        # the image starts, and the kernel silently cold-boots instead.
        parts.append(f"resume={mapper_path}")
        parts.append(f"resume_offset={resume_offset}")

    return " ".join(parts)


def render_config(
    config: InstallConfig,
    cmdline: str,
) -> str:
    """One entry per kernel, default first, fallback second."""
    lines = [
        "# Generated by arch-framework-installer.",
        "timeout: 3",
        "default_entry: 1",
        "",
    ]

    for kernel in config.system.kernels:
        lines.extend(
            [
                f"/Arch Linux ({kernel})",
                "    protocol: linux",
                f"    kernel_path: boot():/vmlinuz-{kernel}",
                f"    kernel_cmdline: {cmdline}",
                f"    module_path: boot():/initramfs-{kernel}.img",
                "",
            ]
        )

    # The fallback image skips autodetected modules, so it still boots when a
    # hardware change makes the tuned initramfs wrong.
    fallback = config.system.kernels[0]
    lines.extend(
        [
            f"/Arch Linux ({fallback}, fallback initramfs)",
            "    protocol: linux",
            f"    kernel_path: boot():/vmlinuz-{fallback}",
            f"    kernel_cmdline: {cmdline}",
            f"    module_path: boot():/initramfs-{fallback}-fallback.img",
            "",
        ]
    )

    return "\n".join(lines)


def install(
    config: InstallConfig,
    target: TargetSystem,
    *,
    luks_uuid: str,
    mapper_path: str,
    resume_offset: str | None,
    runner: CommandRunner | None = None,
) -> None:
    runner = runner or get_runner()

    cmdline = kernel_cmdline(config, luks_uuid, mapper_path, resume_offset)
    target.write(LIMINE_CONFIG, render_config(config, cmdline))

    target.chroot_critical(
        "Installing the Limine EFI binary",
        ["mkdir", "--parents", f"/{LIMINE_DIRECTORY}"],
    )
    target.chroot_critical(
        "Copying BOOTX64.EFI",
        [
            "cp",
            "/usr/share/limine/BOOTX64.EFI",
            f"/{LIMINE_DIRECTORY}/BOOTX64.EFI",
        ],
    )

    log.success("Limine installed.")
    for package in config.bootloader.aur_packages:
        log.warn(
            f"{package} is AUR-only and was not installed. Until it is, "
            "limine.conf must be updated by hand after a kernel change."
        )
