"""System configuration written into the target.

Everything here is rendered from the configuration rather than copied from a
template directory, because every one of these files depends on values only
known at install time — the LUKS UUID, the resume offset, the chosen subvolumes.

The mkinitcpio hook order is the part most worth reading twice: it is what makes
the difference between a machine that unlocks itself and one that drops to a
recovery shell.
"""

from __future__ import annotations

from . import log
from .command import CommandRunner, get_runner
from .disk import filesystem, luks
from .models import InstallConfig
from .target import TargetSystem


def render_fstab(config: InstallConfig, mapper_path: str, efi_uuid: str) -> str:
    """Written by hand rather than with genfstab.

    genfstab records the mapper device by name, and the name only exists because
    crypttab created it, so the ordering is implicit and fragile. Writing it out
    keeps the relationship visible.
    """
    options = config.disk.mount_options
    lines = [
        "# Generated by arch-framework-installer.",
        "# <device> <mount point> <type> <options> <dump> <pass>",
        "",
    ]

    for subvolume, relative in filesystem.mount_order(config.disk):
        mount_point = f"/{relative}" if relative else "/"
        lines.append(
            f"{mapper_path}\t{mount_point}\tbtrfs\tsubvol={subvolume},{options}\t0 0"
        )

    lines.append("")
    lines.append(f"UUID={efi_uuid}\t/boot\tvfat\tdefaults,umask=0077\t0 2")

    if config.swap.hibernation_enabled or config.swap.size.mib:
        lines.append("")
        lines.append("/swap/swapfile\tnone\tswap\tdefaults\t0 0")

    return "\n".join(lines) + "\n"


def render_crypttab(config: InstallConfig, luks_uuid: str) -> str:
    """crypttab.initramfs, not crypttab.

    The root container must be opened by the initramfs, before the real root
    exists. An entry in /etc/crypttab would be read too late to boot.
    """
    return (
        "# Generated by arch-framework-installer.\n"
        "# Opened by the initramfs, before the root filesystem exists.\n"
        f"{config.encryption.mapper_name}\tUUID={luks_uuid}\tnone\t"
        "luks,discard,tpm2-device=auto\n"
    )


def render_mkinitcpio(config: InstallConfig) -> str:
    """systemd hooks, in the order that makes unlocking work.

    ``systemd`` must precede ``sd-encrypt``, and ``sd-encrypt`` must precede
    ``filesystems``: the container has to be open before the root filesystem can
    be found. ``resume`` comes after ``filesystems`` because a hibernation image
    lives in a file on that filesystem, not on a raw device.
    """
    hooks = ["base", "systemd", "autodetect", "microcode", "modconf", "kms", "keyboard"]
    hooks.append("sd-vconsole")
    hooks.append("block")

    if config.encryption.enabled:
        hooks.append("sd-encrypt")

    hooks.append("filesystems")

    if config.swap.hibernation_enabled:
        hooks.append("resume")

    hooks.append("fsck")

    return (
        "# Generated by arch-framework-installer.\n"
        "#\n"
        "# systemd must come before sd-encrypt, and sd-encrypt before\n"
        "# filesystems: the LUKS container has to be open before the root\n"
        "# filesystem can be found. resume comes after filesystems because the\n"
        "# hibernation image is a file on it, not a raw device.\n"
        "MODULES=()\n"
        "BINARIES=()\n"
        "FILES=()\n"
        f"HOOKS=({' '.join(hooks)})\n"
        "COMPRESSION=\"zstd\"\n"
    )


def render_locale_gen(config: InstallConfig) -> str:
    lines = ["# Generated by arch-framework-installer."]
    lines.extend(f"{name} UTF-8" for name in config.locale.locales)
    return "\n".join(lines) + "\n"


def render_hosts(config: InstallConfig) -> str:
    name = config.system.hostname
    return (
        "127.0.0.1\tlocalhost\n"
        "::1\t\tlocalhost\n"
        f"127.0.1.1\t{name}.localdomain\t{name}\n"
    )


def render_vconsole(config: InstallConfig) -> str:
    return f"KEYMAP={config.locale.keymap}\n"


def render_xkb(config: InstallConfig) -> str:
    """Keyboard for the graphical session.

    The console keymap and this use different naming schemes, which is why both
    are written from one pair of values rather than each being set by hand.
    """
    variant = config.locale.xkb_variant
    lines = [
        '# Generated by arch-framework-installer.',
        'Section "InputClass"',
        '    Identifier "system-keyboard"',
        '    MatchIsKeyboard "on"',
        f'    Option "XkbLayout" "{config.locale.xkb_layout}"',
    ]
    if variant:
        lines.append(f'    Option "XkbVariant" "{variant}"')
    lines.append("EndSection")
    return "\n".join(lines) + "\n"


def render_zram(config: InstallConfig) -> str:
    return (
        "# Generated by arch-framework-installer.\n"
        "[zram0]\n"
        "zram-size = min(ram / 2, 8192)\n"
        "compression-algorithm = zstd\n"
    )


def apply(
    config: InstallConfig,
    target: TargetSystem,
    mapper_path: str,
    *,
    runner: CommandRunner | None = None,
) -> None:
    """Write every configuration file and run the commands that consume them."""
    runner = runner or get_runner()

    luks_uuid = luks.partition_uuid(config.disk.system_partition, runner=runner)
    efi_uuid = luks.partition_uuid(config.disk.efi_partition, runner=runner)

    target.write("etc/fstab", render_fstab(config, mapper_path, efi_uuid))

    if config.encryption.enabled:
        target.write("etc/crypttab.initramfs", render_crypttab(config, luks_uuid))

    target.write("etc/hostname", f"{config.system.hostname}\n")
    target.write("etc/hosts", render_hosts(config))
    target.write("etc/locale.gen", render_locale_gen(config))
    target.write("etc/locale.conf", f"LANG={config.locale.locale}\n")
    target.write("etc/vconsole.conf", render_vconsole(config))
    target.write("etc/X11/xorg.conf.d/00-keyboard.conf", render_xkb(config))
    target.write("etc/mkinitcpio.conf", render_mkinitcpio(config))

    if config.swap.zram_enabled:
        target.write("etc/systemd/zram-generator.conf", render_zram(config))

    target.chroot_critical(
        "Generating locales", ["locale-gen"]
    )
    target.chroot_critical(
        f"Setting the timezone to {config.locale.timezone}",
        ["ln", "--symbolic", "--force",
         f"/usr/share/zoneinfo/{config.locale.timezone}", "/etc/localtime"],
    )
    target.chroot_critical("Writing the hardware clock", ["hwclock", "--systohc"])
    target.chroot_critical(
        "Building the initramfs", ["mkinitcpio", "--allpresets"], stream=True
    )

    for service in ("systemd-timesyncd" if config.locale.ntp else None, "iwd", "dhcpcd"):
        if service:
            target.enable_service(service)

    log.success("System configuration written.")
