"""User accounts and sudo.

Passwords reach the target through ``chpasswd`` on stdin. They are never written
to a file inside the target and never appear as command arguments, where the
process list would expose them to every user on the machine.
"""

from __future__ import annotations

from . import log
from .exceptions import StageError
from .models import Credentials, UserConfig
from .target import TargetSystem

SUDO_DROPIN = "etc/sudoers.d/10-wheel"


def render_sudoers() -> str:
    """A drop-in rather than an edit to /etc/sudoers.

    Editing the main file means a package update can conflict with the change;
    a drop-in survives untouched and is obvious to find.
    """
    return (
        "# Generated by arch-framework-installer.\n"
        "%wheel ALL=(ALL:ALL) ALL\n"
    )


def create_users(
    users: UserConfig,
    credentials: Credentials,
    target: TargetSystem,
) -> None:
    if not users.users:
        raise StageError("no user account is configured")

    for user in users.users:
        # useradd accepts a shell that does not exist, and the account is then
        # created unable to log in. Checked here because it is recoverable now
        # and much less so after a reboot.
        if not target.runner or not target.runner.dry_run:
            if not target.path(user.shell.lstrip("/")).exists():
                raise StageError(
                    f"{user.shell} does not exist in the target: {user.name} "
                    "would be created unable to log in. Add the package that "
                    "provides it to a package list."
                )

    if any(user.sudo for user in users.users):
        # Written before the first user is created, so a failure part-way through
        # never leaves an account that believes it has sudo but does not.
        target.write(SUDO_DROPIN, render_sudoers(), mode=0o440)

    for user in users.users:
        target.chroot_critical(
            f"Creating {user.name}",
            [
                "useradd",
                "--create-home",
                "--shell",
                user.shell,
                *(
                    ["--groups", ",".join(user.effective_groups)]
                    if user.effective_groups
                    else []
                ),
                user.name,
            ],
        )

        password = credentials.user_passwords.get(user.name)
        if not password:
            raise StageError(
                f"no password supplied for {user.name}; pass one in the "
                "credentials file or the account would be unusable"
            )

        target.chroot(
            ["chpasswd"],
            input_text=f"{user.name}:{password}\n",
        )
        log.success(f"{user.name} created.")

    if users.root_login_enabled:
        if not credentials.root_password:
            raise StageError("root login is enabled but no root password was supplied")
        target.chroot(
            ["chpasswd"], input_text=f"root:{credentials.root_password}\n"
        )
        log.info("Root password set.")
    else:
        # With a sudo user in place, a loginable root is a second password to
        # protect for no gain.
        target.chroot_critical("Locking the root account", ["passwd", "--lock", "root"])
