#!/usr/bin/env bash

# ==============================================================================
# Module: memory
#
# Purpose:
#   Configure zram, the hibernation swapfile, and the kernel tuning that makes
#   the two coexist.
#
# Idempotent:
#   Yes
# ==============================================================================

if [[ -n "${ARCH_INSTALLER_MEMORY_LOADED:-}" ]]; then return 0; fi
readonly ARCH_INSTALLER_MEMORY_LOADED="true"

# Swap priorities. zram is faster than any disk, so everyday paging must prefer
# it; the swapfile exists for hibernation and as a last resort. Equal priorities
# would make the kernel stripe across both, putting hot pages on disk for no
# reason.
readonly ZRAM_SWAP_PRIORITY=100
readonly SWAPFILE_SWAP_PRIORITY=10

readonly SWAP_SUBVOLUME="@swap"
readonly SWAP_MOUNTPOINT="/swap"
readonly SWAPFILE_PATH="/swap/swapfile"

readonly ZRAM_CONFIG_PATH='/etc/systemd/zram-generator.conf'
readonly ZRAM_SYSCTL_PATH='/etc/sysctl.d/99-zram.conf'

# ------------------------------------------------------------------------------
# Initramfs hooks
# ------------------------------------------------------------------------------

# Hook order is what makes unlocking and resuming work.
#
#   systemd     before sd-encrypt  — sd-encrypt needs its environment
#   sd-encrypt  before filesystems — the container must be open before the root
#                                    filesystem can be found
#   resume      after  filesystems — the hibernation image is a file on that
#                                    filesystem, not a raw device
build_mkinitcpio_hooks() {
    local hooks=(
        base systemd autodetect microcode modconf kms keyboard sd-vconsole block
    )

    if [[ "${LUKS_ENABLED}" == "true" ]]; then
        hooks+=(sd-encrypt)
    fi

    hooks+=(filesystems)

    if hibernation_enabled; then
        hooks+=(resume)
    fi

    hooks+=(fsck)

    printf 'HOOKS=(%s)' "${hooks[*]}"
}

# ------------------------------------------------------------------------------
# zram
# ------------------------------------------------------------------------------

configure_zram() {
    if [[ "${ZRAM_ENABLED}" != "true" ]]; then
        info "Zram is disabled; removing the installer-managed target configuration."
        run_command rm -f "${MOUNT_ROOT}${ZRAM_CONFIG_PATH}" || return 1
        run_command rm -f "${MOUNT_ROOT}${ZRAM_SYSCTL_PATH}"
        return
    fi

    write_target_file "${ZRAM_CONFIG_PATH}" "[zram0]
zram-size = ram / 2
compression-algorithm = zstd
swap-priority = ${ZRAM_SWAP_PRIORITY}
" || return 1

    configure_zram_sysctl
}

configure_zram_sysctl() {
    # Without this, zram is created and then barely used.
    #
    # The default vm.swappiness of 60 is tuned for swap on a rotating disk, where
    # paging out is expensive and the kernel should avoid it. zram is RAM-speed,
    # so the same caution makes it sit idle while the system reclaims page cache
    # instead — the "configured but does nothing" symptom.
    #
    # 180 is the value suggested once swap is roughly as fast as memory.
    # page-cluster 0 disables read-ahead: batching pays off on a disk and only
    # costs decompression work on zram.
    write_target_file "${ZRAM_SYSCTL_PATH}" '# Generated by arch-framework-installer.
#
# Tuned for compressed swap in RAM, not for swap on a disk.
vm.swappiness = 180
vm.page-cluster = 0
vm.watermark_boost_factor = 0
vm.watermark_scale_factor = 125
'
}

verify_zram_configuration() {
    local config_path="${MOUNT_ROOT}${ZRAM_CONFIG_PATH}"
    local sysctl_path="${MOUNT_ROOT}${ZRAM_SYSCTL_PATH}"

    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        return 0
    fi

    if [[ "${ZRAM_ENABLED}" == "true" ]]; then
        [[ -s "${config_path}" ]] || return 1
        grep -Fq 'compression-algorithm = zstd' "${config_path}" || return 1
        grep -Fq "swap-priority = ${ZRAM_SWAP_PRIORITY}" "${config_path}" || return 1
        [[ -s "${sysctl_path}" ]] || return 1
        grep -Fq 'vm.swappiness = 180' "${sysctl_path}"
        return
    fi

    [[ ! -e "${config_path}" ]] && [[ ! -e "${sysctl_path}" ]]
}

# ------------------------------------------------------------------------------
# Hibernation swapfile
# ------------------------------------------------------------------------------

hibernation_enabled() {
    [[ "${HIBERNATION_ENABLED}" == "true" ]]
}

swap_size_is_zero() {
    [[ "${SWAP_SIZE}" =~ ^0[A-Za-z]*$ ]]
}

swapfile_required() {
    ! swap_size_is_zero
}

validate_swap_dependencies() {
    swapfile_required || return 0
    require_commands_for_mode "Swapfile" btrfs swapon
}

# A hibernation image is the contents of RAM. A swapfile smaller than RAM cannot
# hold it, and the kernel discovers that only when the write fails part way
# through suspending.
validate_swap_size_for_hibernation() {
    local swap_mib
    local memory_bytes
    local memory_mib

    hibernation_enabled || return 0

    if swap_size_is_zero; then
        error "HIBERNATION_ENABLED=true requires SWAP_SIZE to be greater than zero."
        return 1
    fi

    swap_mib="$(size_to_mib "${SWAP_SIZE}")" || return 1
    memory_bytes="$(get_memory_bytes)" || return 0
    memory_mib=$((memory_bytes / 1024 / 1024))

    if ((swap_mib < memory_mib)); then
        error "SWAP_SIZE (${SWAP_SIZE}) is smaller than installed memory (${memory_mib}MiB)."
        error "A hibernation image is the contents of RAM and would not fit."
        return 1
    fi

    success "Swap size is sufficient for hibernation."
}

create_swapfile() {
    local swap_mib

    if ! swapfile_required; then
        info "SWAP_SIZE is zero; no swapfile is created."
        return 0
    fi

    swap_mib="$(size_to_mib "${SWAP_SIZE}")" || return 1

    # btrfs mkswapfile handles what dd plus mkswap does not: it disables
    # copy-on-write and compression on the file, both of which corrupt a
    # swapfile. Suffix is lowercase to match the documented k/m/g form.
    run_command btrfs filesystem mkswapfile --size "${swap_mib}m" \
        "${MOUNT_ROOT}${SWAPFILE_PATH}" || return 1
    run_command swapon --priority "${SWAPFILE_SWAP_PRIORITY}" \
        "${MOUNT_ROOT}${SWAPFILE_PATH}"
}

# Physical offset of the swapfile within its device.
#
# The kernel needs both resume= and resume_offset=. With only the device it knows
# where to look but not where the image starts, and it silently cold-boots
# instead of reporting a problem.
get_swapfile_resume_offset() {
    if [[ "${DRY_RUN:-false}" == "true" ]]; then
        printf '%s' 'DRY-RUN-RESUME-OFFSET'
        return 0
    fi

    btrfs inspect-internal map-swapfile --resume-offset \
        "${MOUNT_ROOT}${SWAPFILE_PATH}"
}

swapfile_fstab_entry() {
    swapfile_required || return 0

    printf '# Swapfile. Lower priority than zram: zram takes everyday paging,\n'
    printf '# this exists for hibernation.\n'
    printf '%s none swap defaults,pri=%s 0 0\n' \
        "${SWAPFILE_PATH}" "${SWAPFILE_SWAP_PRIORITY}"
}

verify_swapfile() {
    [[ "${DRY_RUN:-false}" == "true" ]] && return 0
    swapfile_required || return 0

    if [[ ! -f "${MOUNT_ROOT}${SWAPFILE_PATH}" ]]; then
        error "The swapfile is missing: ${MOUNT_ROOT}${SWAPFILE_PATH}"
        return 1
    fi

    # A copy-on-write swapfile corrupts. btrfs mkswapfile clears the attribute,
    # so finding it unset means something else created the file.
    if ! lsattr -d "${MOUNT_ROOT}${SWAPFILE_PATH}" 2>/dev/null | grep -q 'C'; then
        error "Copy-on-write is not disabled on the swapfile."
        return 1
    fi
}

verify_hibernation_configuration() {
    local mkinitcpio_path="${MOUNT_ROOT}/etc/mkinitcpio.conf"
    local limine_path="${MOUNT_ROOT}/boot/limine.conf"

    [[ "${DRY_RUN:-false}" == "true" ]] && return 0
    hibernation_enabled || return 0

    if ! grep -Fq 'resume' "${mkinitcpio_path}"; then
        error "Hibernation is enabled but the resume hook is missing from mkinitcpio.conf."
        return 1
    fi

    if ! grep -Fq 'resume_offset=' "${limine_path}"; then
        error "Hibernation is enabled but resume_offset is missing from limine.conf."
        return 1
    fi
}
