#!/usr/bin/env bash

# ==============================================================================
# Module: snapshots
#
# Purpose:
#   Configure Snapper and the pacman hooks that make rollback possible.
#
# Idempotent:
#   Yes
# ==============================================================================

if [[ -n "${ARCH_INSTALLER_SNAPSHOTS_LOADED:-}" ]]; then return 0; fi
readonly ARCH_INSTALLER_SNAPSHOTS_LOADED="true"

readonly SNAPPER_CONFIG_PATH='/etc/snapper/configs/root'
readonly SNAPPER_DEFAULTS_PATH='/etc/conf.d/snapper'
readonly SNAP_PAC_CONFIG_PATH='/etc/snap-pac.ini'
readonly SNAPSHOTS_MOUNTPOINT='/.snapshots'

# ------------------------------------------------------------------------------
# Snapper
# ------------------------------------------------------------------------------

# Written directly rather than through `snapper create-config`.
#
# create-config wants to create /.snapshots itself and fails when the path
# already exists. Here @snapshots is a separate subvolume, mounted there before
# snapper is ever installed, which is what keeps snapshots out of the snapshots
# taken of the root subvolume.
configure_snapper() {
    write_target_file "${SNAPPER_CONFIG_PATH}" 'SUBVOLUME="/"
FSTYPE="btrfs"
ALLOW_USERS=""
ALLOW_GROUPS="wheel"
SYNC_ACL="yes"
TIMELINE_CREATE="yes"
TIMELINE_CLEANUP="yes"
TIMELINE_MIN_AGE="1800"
TIMELINE_LIMIT_HOURLY="6"
TIMELINE_LIMIT_DAILY="7"
TIMELINE_LIMIT_WEEKLY="4"
TIMELINE_LIMIT_MONTHLY="2"
TIMELINE_LIMIT_YEARLY="0"
NUMBER_CLEANUP="yes"
NUMBER_MIN_AGE="1800"
NUMBER_LIMIT="20"
NUMBER_LIMIT_IMPORTANT="10"
EMPTY_PRE_POST_CLEANUP="yes"
EMPTY_PRE_POST_MIN_AGE="1800"
' || return 1

    write_target_file "${SNAPPER_DEFAULTS_PATH}" 'SNAPPER_CONFIGS="root"
' || return 1

    configure_snapshot_pacman_hooks || return 1
    secure_snapshots_directory
}

# A snapshot can contain any file the root filesystem contained, so the directory
# listing them must not be world-readable.
secure_snapshots_directory() {
    [[ "${DRY_RUN:-false}" == "true" ]] && return 0
    run_command chmod 750 "${MOUNT_ROOT}${SNAPSHOTS_MOUNTPOINT}"
}

# ------------------------------------------------------------------------------
# Pacman integration
# ------------------------------------------------------------------------------

# snap-pac takes a snapshot before and after every pacman transaction, which is
# what the documented rollback story needs: a snapshot from immediately before
# the transaction that broke things. The timeline alone can leave an hour of
# unrelated changes in between, so rolling back would undo more than the update.
#
# The package snapshots the root configuration by default, so this file is not
# required to make it work. What it adds is marking kernel updates and full
# system upgrades as important, which is what gives
# NUMBER_LIMIT_IMPORTANT any meaning — without it that setting retains nothing,
# because nothing is ever flagged.
#
# Keys and the .ini path are the ones snap-pac documents; the values are Python
# literals, hence True rather than yes.
configure_snapshot_pacman_hooks() {
    write_target_file "${SNAP_PAC_CONFIG_PATH}" '# Generated by arch-framework-installer.
#
# snap-pac already snapshots the root configuration by default. This marks the
# transactions worth keeping longer, so NUMBER_LIMIT_IMPORTANT in the snapper
# profile has something to retain.
[root]
snapshot = True
important_packages = ["linux", "linux-lts", "limine", "systemd", "cryptsetup"]
important_commands = ["pacman -Syu", "pacman -Syyu"]
desc_limit = 128
'
}

# ------------------------------------------------------------------------------
# Verification
# ------------------------------------------------------------------------------

verify_snapshot_configuration() {
    local config_path="${MOUNT_ROOT}${SNAPPER_CONFIG_PATH}"

    [[ "${DRY_RUN:-false}" == "true" ]] && return 0

    verify_target_file "${SNAPPER_CONFIG_PATH}" || {
        error "The Snapper root profile is missing."
        return 1
    }

    grep -Fq 'SUBVOLUME="/"' "${config_path}" || {
        error "The Snapper root profile does not describe the root subvolume."
        return 1
    }

    verify_target_file "${SNAP_PAC_CONFIG_PATH}" || {
        error "snap-pac is not configured; important updates would not be flagged."
        return 1
    }

    # The configuration file is optional for snap-pac, so its presence proves
    # nothing about the package. The pacman hooks are what actually run.
    if ! find "${MOUNT_ROOT}/usr/share/libalpm/hooks" -name '*snap-pac*' -print -quit \
        2>/dev/null | grep -q .; then
        error "The snap-pac pacman hooks are missing; updates would not be snapshotted."
        return 1
    fi

    # A configuration naming /.snapshots while nothing is mounted there would
    # write snapshots into the root subvolume. The root would then contain its
    # own snapshots, and could not be rolled back cleanly.
    findmnt --mountpoint "${MOUNT_ROOT}${SNAPSHOTS_MOUNTPOINT}" >/dev/null || {
        error "${SNAPSHOTS_MOUNTPOINT} is not a separate mounted subvolume."
        return 1
    }
}
